apiVersion: v1
kind: ServiceAccount
metadata:
  name: companion-workload-identity-sa
  annotations:
    azure.workload.identity/client-id: "535f2879-34e4-48bb-881e-087c48e26a16"
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: companion
  annotations:
    nginx.ingress.kubernetes.io/cors-allow-origin: "https://app.askturing.ai"
    nginx.ingress.kubernetes.io/limit-rps: "200"
    nginx.ingress.kubernetes.io/limit-connections: "100"
spec:
  rules:
  - host: companion.prod.askturing.ai
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: companion
            port:
              number: 80
  tls:
  - hosts:
    - companion.prod.askturing.ai
    secretName: companion-tls-prod
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: companion
spec:
  minReplicas: 3
  maxReplicas: 20
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 60
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 50
        periodSeconds: 60
      selectPolicy: Min
    scaleUp:
      stabilizationWindowSeconds: 30
      policies:
      - type: Percent
        value: 100
        periodSeconds: 15
      - type: Pods
        value: 4
        periodSeconds: 15
      selectPolicy: Max
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: companion
spec:
  template:
    spec:
      containers:
      - name: companion
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
        env:
        - name: NODE_ENV
          value: "production"
        - name: COMPANION_PERIODIC_PING_COUNT
          value: "0"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: companion-redis
spec:
  template:
    spec:
      containers:
      - name: redis
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "300m"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: companion-redis-pvc
spec:
  resources:
    requests:
      storage: 10Gi
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: companion
spec:
  minAvailable: 2
---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: azure-companion-store
spec:
  provider:
    azurekv:
      vaultUrl: "https://askturing-prod.vault.azure.net/"