apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: prod

resources:
  - ../../base

patches:
  - path: companion-patches.yaml

configMapGenerator:
- name: companion-config
  behavior: merge
  literals:
  - COMPANION_DOMAIN=companion.prod.askturing.ai
  - COMPANION_PROTOCOL=https
  - COMPANION_SELF_ENDPOINT=companion.prod.askturing.ai
  - COMPANION_CLIENT_ORIGINS=https://app.askturing.ai
  - COMPANION_UPLOAD_URLS=https://backend.askturing.ai/api/upload
  - COMPANION_DEBUG=false
  - COMPANION_METRICS=true

images:
- name: transloadit/companion
  newTag: "4.13.1"