apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: companion-apps
  namespace: argocd
  labels:
    app.kubernetes.io/name: companion
    app.kubernetes.io/part-of: askturing-platform
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/AskTuringAI/companion-ops
    targetRevision: main
    path: argocd/applications
    directory:
      include: "*.yaml"
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m