apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: companion-prod
  namespace: argocd
  labels:
    environment: prod
    component: companion
  annotations:
    notifications.argoproj.io/subscribe.discord: ""
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/AskTuringAI/companion-ops
    targetRevision: main
    path: environments/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: prod
  ignoreDifferences:
  - group: apps
    kind: Deployment
    jsonPointers:
    - /spec/replicas
  syncPolicy:
    # Manual sync for production
    syncOptions:
    - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m