apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: companion-secrets
  annotations:
    argocd.argoproj.io/sync-wave: "-15"
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: azure-companion-store
    kind: SecretStore
  target:
    name: companion-secrets
    creationPolicy: Owner
  data:
  # Core Configuration
  - secretKey: COMPANION_SECRET
    remoteRef:
      key: COMPANION-SECRET
  - secretKey: COMPANION_PREAUTH_SECRET
    remoteRef:
      key: COMPANION-PREAUTH-SECRET
  
  # Google Drive OAuth
  - secretKey: COMPANION_GOOGLE_KEY
    remoteRef:
      key: GOOGLE-CLIENT-ID
  - secretKey: COMPANION_GOOGLE_SECRET
    remoteRef:
      key: GOOGLE-CLIENT-SECRET
  
  # # Dropbox OAuth (optional)
  # - secretKey: COMPANION_DROPBOX_KEY
  #   remoteRef:
  #     key: DROPBOX-APP-KEY
  # - secretKey: COMPANION_DROPBOX_SECRET
  #   remoteRef:
  #     key: DROPBOX-APP-SECRET
  
  # # OneDrive OAuth (optional)
  # - secretKey: COMPANION_ONEDRIVE_KEY
  #   remoteRef:
  #     key: MS-CLIENT-ID
  # - secretKey: COMPANION_ONEDRIVE_SECRET
  #   remoteRef:
  #     key: MS-CLIENT-SECRET